# ---------- Overriding hydra default configs ----------
hydra:
  job:
    name: train
    chdir: true
  run:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}/single
  sweep:
    dir: ${dir.output_dir}/${hydra.job.name}/${exp_name}
    subdir: run${hydra.job.num}

defaults:
  - _self_
  - dir: local
  - model: Spec2DCNN 
  - feature_extractor: CNNSpectrogram
  - decoder: UNet1DDecoder
  - split: stratify_fold_1
  - features: base
  - post_process: train
  - ignore: zero
  - loss: bce

datamodule:
  how: random # random, stride, overlap
  train_stride: 3600 # 3h=2160, 5h=3600, 8h=5760
  overlap: 0 
  zero_periodicity: false

seed: 42
exp_name: dummy
duration: 5760 # (1step 5秒なので) duration * 5 = 秒数。 eg) 5760 * 5 = 28800s = 8h
downsample_rate: 2
upsample_rate: 1

averaged_model:
  how: None # ema, avg
  ema_decay: 0.999


# training
epoch: 50
batch_size: 32
num_workers: 8
accelerator: auto
use_amp: true
debug: false
gradient_clip_val: 1.0
accumulate_grad_batches: 1
monitor: val_loss
monitor_mode: min
check_val_every_n_epoch: 1

# Dataset
offset: 10
sigma: 10
bg_sampling_rate: 0.5
sigma_decay:  # 0.95
sleep_decay: # 0.90

# augmentation
augmentation:
  mixup_prob: 0.0
  mixup_alpha: 0.4
  cutmix_prob: 0.0
  cutmix_alpha: 0.4
  

# label
labels:
  - "awake"
  - "event_onset"
  - "event_wakeup"
label_weight:
  - 1.0
  - 1.0
  - 1.0
pos_weight:
  - 1.0
  - 1.0
  - 1.0


# optimizer
optimizer:
  lr: 0.0005

# scheduler
scheduler:
  use_warmup: False
