wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700038228.661647
    t:
      1:
      - 50
      - 55
      - 105
      2:
      - 50
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.15.9
      8:
      - 1
      - 5
